title: Firebolt documentation
description: >-
  User and developer documentation for the Firebolt data warehouse.
domain: docs.firebolt.io
url: "https://docs.firebolt.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: firebolt-db/just-the-docs
logo: "/assets/images/logo_website.svg"
color_scheme: firebolt
search_enabled: true

# Jekyll plugins
plugins:
  - jekyll-seo-tag
  - jekyll-lnr-js-search

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Link in upper right

aux_links:
  "SCHEDULE A CALL":
    - "https:///www.firebolt.io/getting-started-now"

# Google Analytics tracking
ga_tracking: UA-142599515-1
ga_tracking_anonymize_ip: true

footer_content: "<a href=\"mailto:docs@firebolt.io\">Send feedback</a>"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit on GitHub"
gh_edit_repository: "https://github.com/firebolt-db/firebolt-db.github.io" # the github URL for your repo
gh_edit_branch: "gh-pages"
gh_edit_source: docs
gh_edit_view_mode: "edit"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
