name: Sync PR to Preview
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v2

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'

      - name: Build
        run: |
          cd build
          git checkout -b newbranch
          git pull ${{ github.event.pull_request.head.url }} ${{ github.head_ref }}
          git push origin


      - name: Checkout Staging Target
        uses: actions/checkout@v2
        with:
          repository: molly-firebolt/super-robot
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: 'deploy'
      
      - name: Push files to target
        run: |
          cp -r build/* deploy
          cd deploy
          git add -A
          git commit -m $GITHUB_SHA
          git push